config/routes.rb
Rails.application.routes.draw do
  devise_for :users, :controllers => {
    :registrations => "users/registrations",
  }

  root to: "homes#top"
  get "home/about" => "homes#about"
  resources :books, only:[:index, :create, :show, :edit, :update, :destroy]
  resources :users, only:[:index, :show, :edit, :update]
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/book.rb
class Book < ApplicationRecord
  belongs_to :user

  validates :title, presence: true
  validates :body ,presence: true
  validates :body, length: {maximum: 200}

end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable

  has_many :books, dependent: :destroy

  validates :name, uniqueness: true
  validates :name, length: {in: 2..20}
  validates :introduction, length: {maximum: 50}

  attachment :profile_image

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  before_action :authenticate_user!, except: [:top, :about]

  before_action :configure_permitted_parameters, if: :devise_controller?

  def after_sign_in_path_for(resource)
    user_path(resource)
  end

  def after_sign_up_path_for(resource)
    user_path(resource)
  end

  protected
  def configure_permitted_parameters
    devise_parameter_sanitizer.permit(:sign_up, keys:[:email])
  end

end

app/controllers/books_controller.rb
class BooksController < ApplicationController
  def index
    @book=Book.new
    @books=Book.all
  end

  def create
    @book=Book.new(book_params)
    @book.user_id=current_user.id
    @books=Book.all
    if @book.save
      redirect_to book_path(@book.id)
      flash[:notice]="You have created book successfully."
    else
      render :index
    end
  end

  def show
    @book=Book.new
    @books=Book.find(params[:id])
    @user=User.find_by(id: @books.user_id)
  end

  def edit
    @book=Book.find(params[:id])
    if @book.user == current_user
      render :edit
    else
      redirect_to books_path
    end
  end

  def update
    @book=Book.find(params[:id])
    if @book.update(book_params)
      redirect_to book_path(@book.id)
      flash[:notice]="You have updated book successfully."
    else
      render :edit
    end
  end

  def destroy
    @book=Book.find(params[:id])
    @book.destroy
    redirect_to books_path
  end

  private
  def book_params
    params.require(:book).permit(:title, :body, :user_id)
  end

end

app/controllers/homes_controller.rb
class HomesController < ApplicationController
  def top
  end
  
  def about
  end
  
end

app/controllers/users/confirmations_controller.rb
# frozen_string_literal: true

class Users::ConfirmationsController < Devise::ConfirmationsController
  # GET /resource/confirmation/new
  # def new
  #   super
  # end

  # POST /resource/confirmation
  # def create
  #   super
  # end

  # GET /resource/confirmation?confirmation_token=abcdef
  # def show
  #   super
  # end

  # protected

  # The path used after resending confirmation instructions.
  # def after_resending_confirmation_instructions_path_for(resource_name)
  #   super(resource_name)
  # end

  # The path used after confirmation.
  # def after_confirmation_path_for(resource_name, resource)
  #   super(resource_name, resource)
  # end
end

app/controllers/users/omniauth_callbacks_controller.rb
# frozen_string_literal: true

class Users::OmniauthCallbacksController < Devise::OmniauthCallbacksController
  # You should configure your model like this:
  # devise :omniauthable, omniauth_providers: [:twitter]

  # You should also create an action method in this controller like this:
  # def twitter
  # end

  # More info at:
  # https://github.com/heartcombo/devise#omniauth

  # GET|POST /resource/auth/twitter
  # def passthru
  #   super
  # end

  # GET|POST /users/auth/twitter/callback
  # def failure
  #   super
  # end

  # protected

  # The path used when OmniAuth fails
  # def after_omniauth_failure_path_for(scope)
  #   super(scope)
  # end
end

app/controllers/users/passwords_controller.rb
# frozen_string_literal: true

class Users::PasswordsController < Devise::PasswordsController
  # GET /resource/password/new
  # def new
  #   super
  # end

  # POST /resource/password
  # def create
  #   super
  # end

  # GET /resource/password/edit?reset_password_token=abcdef
  # def edit
  #   super
  # end

  # PUT /resource/password
  # def update
  #   super
  # end

  # protected

  # def after_resetting_password_path_for(resource)
  #   super(resource)
  # end

  # The path used after sending reset password instructions
  # def after_sending_reset_password_instructions_path_for(resource_name)
  #   super(resource_name)
  # end
end

app/controllers/users/registrations_controller.rb
# frozen_string_literal: true

class Users::RegistrationsController < Devise::RegistrationsController
  # before_action :configure_sign_up_params, only: [:create]
  # before_action :configure_account_update_params, only: [:update]

  # GET /resource/sign_up
  # def new
  #   super
  # end

  # POST /resource
  def create
    super
    ThanksMailer.thanks_mail(params[:user][:email],params[:user][:name]).deliver
  end

  # GET /resource/edit
  # def edit
  #   super
  # end

  # PUT /resource
  # def update
  #   super
  # end

  # DELETE /resource
  # def destroy
  #   super
  # end

  # GET /resource/cancel
  # Forces the session data which is usually expired after sign
  # in to be expired now. This is useful if the user wants to
  # cancel oauth signing in/up in the middle of the process,
  # removing all OAuth session data.
  # def cancel
  #   super
  # end

  # protected

  # If you have extra params to permit, append them to the sanitizer.
  # def configure_sign_up_params
  #   devise_parameter_sanitizer.permit(:sign_up, keys: [:attribute])
  # end

  # If you have extra params to permit, append them to the sanitizer.
  # def configure_account_update_params
  #   devise_parameter_sanitizer.permit(:account_update, keys: [:attribute])
  # end

  # The path used after sign up.
  # def after_sign_up_path_for(resource)
  #   super(resource)
  # end

  # The path used after sign up for inactive accounts.
  def after_inactive_sign_up_path_for(resource)
    user_path(resource)
  end
end

app/controllers/users/sessions_controller.rb
# frozen_string_literal: true

class Users::SessionsController < Devise::SessionsController
  # before_action :configure_sign_in_params, only: [:create]

  # GET /resource/sign_in
  # def new
  #   super
  # end

  # POST /resource/sign_in
  # def create
  #   super
  # end

  # DELETE /resource/sign_out
  # def destroy
  #   super
  # end

  # protected

  # If you have extra params to permit, append them to the sanitizer.
  # def configure_sign_in_params
  #   devise_parameter_sanitizer.permit(:sign_in, keys: [:attribute])
  # end
end

app/controllers/users/unlocks_controller.rb
# frozen_string_literal: true

class Users::UnlocksController < Devise::UnlocksController
  # GET /resource/unlock/new
  # def new
  #   super
  # end

  # POST /resource/unlock
  # def create
  #   super
  # end

  # GET /resource/unlock?unlock_token=abcdef
  # def show
  #   super
  # end

  # protected

  # The path used after sending unlock password instructions
  # def after_sending_unlock_instructions_path_for(resource)
  #   super(resource)
  # end

  # The path used after unlocking the resource
  # def after_unlock_path_for(resource)
  #   super(resource)
  # end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  def index
    @user=User.find(current_user.id)
    @book=Book.new
    @users=User.all
  end

  def show
    @user=User.find_by(id: params[:id])
    @book=Book.new
    @books=@user.books
  end

  def edit
    @user=User.find(params[:id])
    if @user == current_user
      render :edit
    else
      redirect_to user_path(current_user.id)
    end
  end

  def update
    @user=User.find(params[:id])
    if @user.update(user_params)
      redirect_to user_path(@user.id)
      flash[:notice]="You have updated user successfully."
    else
      render :edit
    end
  end
  

  private
  def user_params
    params.require(:user).permit(:name, :introduction, :profile_image)
  end

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/books_helper.rb
module BooksHelper
end

app/helpers/homes_helper.rb
module HomesHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/books/edit.html.erb
<div class="container">
  <div class="row">
    <div class="col-sm-12 col-md-8 col-lg-5 px-5 px-sm-0 mx-auto">
      <h1>Editing Book</h1>

      <%= form_with model: @book, local: true do |f| %>
        <%= render "layouts/error_form", model: f.object %>

        <div class="form-group">
          <label>Title</label>
          <%= f.text_field :title, class: "form-control" %>
        </div>

        <div class="form-group">
          <label>Opinion</label>
          <%= f.text_area :body, class: "form-control" %>
        </div>

        <div class="form-group">
          <%= f.submit "Update Book", class: "btn btn-success" %>
        </div>
      <% end %>

      <%= link_to "Show", book_path(@book.id) %>
       |
      <%= link_to "Back", books_path %>

    </div>
  </div>
</div>

app/views/books/index.html.erb
<div class="container px-5 px-sm-0">
  <%= render "layouts/error_form", model: @book %>
  <div class="row">
    <div class="col-md-3">
      <%= render partial: "layouts/user_info", locals: {user: current_user} %>
      <%= render partial: "layouts/new_book", locals: {book: @book} %>
    </div>

    <div class="col-md-8 offset-md-1">
      <h2>Books</h2>

      <table class="table table-hober table-inverse">
        <thead>
          <tr>
            <th></th>
            <th>Title</th>
            <th>Opinion</th>
            <th colspan="3"></th>
          </tr>
        </thead>

        <tbody>
          <% @books.each do |book| %>
          <tr>
            <td>
              <%= link_to user_path(book.user.id) do %>
                <%= attachment_image_tag book.user, :profile_image, size: "40x40", fallback: "no_image.jpeg" %>
              <% end %>
            </td>
            <td><%= link_to book.title, book_path(book.id) %></td>
            <td><%= book.body %></td>
          </tr>
          <% end %>
        </tbody>

      </table>
    </div>

  </div>
</div>

app/views/books/show.html.erb
<div class="container">
  <div class="row">
    <div class="col-md-3">
      <%= render partial: "layouts/user_info", locals: {user: @user} %>
      <%= render partial: "layouts/new_book", locals: {book: @book} %>
    </div>

    <div class="col-md-8 offset-md-1">
      <h2>Book detail</h2>

      <table class="table">
        <tbody>
          <tr>
            <td>
              <%= link_to user_path(@user.id) do %>
                <%= attachment_image_tag @user, :profile_image, size: "40x40", fallback: "no_image.jpeg" %><br />
                <%= @user.name %>
              <% end %>
            </td>
            <td><%= link_to @books.title, book_path(@books.id) %></td>
            <td><%= @books.body %></td>
            <% if @user.id == current_user.id %>
            <td><%= link_to "Edit", edit_book_path(@books.id), class: "btn btn-sm btn-success" %></td>
            <td><%= link_to "Destroy", book_path(@books.id), method: :delete, class: "btn btn-sm btn-danger" %></td>
            <% end %>
          </tr>
        </tbody>
      </table>

    </div>
  </div>
</div>

app/views/homes/about.html.erb
<div class="container">
  <div class="row">
    <h1 class="px-3 mx-auto">
      Welcome to <i class="fas fa-book"></i><strong>Bookers</strong>!
    </h1>
  </div>
</div>

app/views/homes/top.html.erb
<div class="container">
  <div class="row">
    <div class="mx-auto col-11 col-sm-10 col-lg-8 col-xl-6">
      <h1>
        welcome to <i class="fas fa-book"></i><strong>Bookers</strong> !!
      </h1>

      <p>
        In
        <i class="fas fa-book"></i>
        <strong>Bookers</strong>
        ,
      </p>

      <p>
        you can share and exchange your opinions , inpressions , and emotions
      </p>

      <p>about various books!</p>

      <div class="btn-wrapper col-10 mx-auto">
        <div class="row">
          <%= link_to "Log in", new_user_session_path, class: "btn btn-sm btn-info btn-block mb-3" %>
        </div>
        <div class="row">
          <%= link_to "Sign Up", new_user_registration_path, class: "btn btn-sm btn-success btn-block" %>
        </div>
      </div>

    </div>
  </div>
</div>

app/views/layouts/_error_form.html.erb
<% if model.errors.any? %>
  <div id = "error_explanation">
    <h3>
      <%= model.errors.count %> errors prohibited this obj from being saved:
    </h3>

    <ul>
      <% model.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
    </ul>
  </div>
<% end %>

app/views/layouts/_new_book.html.erb
<h2 class="mt-3">New book</h2>

<%= form_with model: book, local: true do |f| %>
  <div class="form-group">
    <label>Title</label>
    <%= f.text_field :title, class: "form-control" %>
  </div>

  <div class="form-group">
    <label>Opinion</label>
    <%= f.text_area :body, class: "form-control" %>
  </div>

  <div class="form-group">
    <%= f.submit "Create Book", class: "btn btn-success" %>
  </div>
<% end %>

app/views/layouts/_user_info.html.erb
<h2>User info</h2>

<p><%= attachment_image_tag user, :profile_image, size: "100x100", fallback: "no_image.jpeg" %></p>

<table class="table">
  <tbody>
    <tr></tr>
    <tr>
      <th>name</th>
      <th><%= user.name %></th>
    </tr>
    <tr>
      <th>introduction</th>
      <th><%= user.introduction %></th>
    </tr>
  </tbody>
</table>

<div class="row">
    <%= link_to edit_user_path(user.id), class: "btn btn-sm btn-outline-secondary btn-block" do %>
      <i class="fas fa-user-cog"></i>
    <% end %>

</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Bookers2</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <script src="https://kit.fontawesome.com/d903263f9b.js" crossorigin="anonymous"></script>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>

    <header>
      <nav class="navbar navbar-expand-lg navbar-dark bg-dark">
        <div class="container">
          <a class="navbar-brand" href="/">Bookers</a>

          <button class="navbar-toggler" type="button", data-toggle="collapse", data-target="#navbarNavDropdown" aria-controls="navbarNavDropdown" aria-expanded="false" aria-label="Toggle navigation">
            <span class="navbar-toggler-icon"></span>
          </button>

          <div class="navbar-collapse collapse" id="navbarNavDropdown">
            <ul class="navbar-nav ml-auto">
              <% if user_signed_in? %>
              <li class="nav-item">
                <%= link_to " Home", user_path(current_user.id), class: "fas fa-home nav-link text-light" %>
              </li>
              <li class="nav-item">
                <%= link_to " Users", users_path, class: "fas fa-users nav-link text-light" %>
              </li>
              <li class="nav-item">
                <%= link_to " Books", books_path, class: "fas fa-book-open nav-link text-light" %>
              </li>
              <li class="nav-item">
                <%= link_to " logout", destroy_user_session_path, method: :delete, class: "fas fa-sign-out-alt nav-link text-light" %>
              </li>

              <% else %>
              <li class="nav-item">
                <%= link_to " Home", root_path, class: "fas fa-home nav-link text-light" %>
              </li>
              <li class="nav-item">
                <%= link_to " About", home_about_path, class: "fas fa-link nav-link text-light" %>
              </li>
              <li class="nav-item">
                <%= link_to " sign up", new_user_registration_path, class: "fas fa-user-plus nav-link text-light" %>
              </li>
              <li class="nav-item">
                <%= link_to " login", new_user_session_path, class: "fas fa-sign-in-alt nav-link text-light" %>
              </li>
              <% end %>
            </ul>
          </div>

        </div>
      </nav>
    </header>

    <main>
      <% flash.each do |key, value| %>
          <%= content_tag(:div, value, class: "#{key}") %>
      <% end %>

      <%= yield %>
    </main>

    <footer>
      <div class="container mt-5">
        <div class="row">
          <div class="mx-auto">
            <p>CopyRight Infratop.inc</p>
          </div>
        </div>
      </div>
    </footer>

  </body>
</html>

app/views/users/edit.html.erb
<div class="container">
  <div class="row">
    <div class="col-sm-12 col-md-8 col-lg-5 px-5 px-sm-0 mx-auto">
      <h2>User info</h2>

      <%= form_with model: @user, local: true do |f| %>
        <%= render "layouts/error_form", model: f.object %>

        <div class="form-group">
          <label>Name</label>
          <%= f.text_field :name, class: "form-control" %>
        </div>

        <div class="form-group">
          <label>Imgae</label>
          <%= f.attachment_field :profile_image, class: "form-control-file" %>
        </div>

        <div class="form-group">
          <label>Introduction</label>
          <%= f.text_area :introduction, class: "form-control" %>
        </div>

        <div class="form-group">
          <%= f.submit "Update User", class: "btn btn-secondary" %>
        </div>

      <% end %>

    </div>
  </div>
</div>

app/views/users/index.html.erb
<div class="container px-5 px-sm-0">
  <div class="row">
    <div class="col-md-3">
      <%= render partial: "layouts/user_info", locals: {user: @user} %>
      <%= render partial: "layouts/new_book", locals: {book: @book} %>
    </div>

    <div class="col-md-8 offset-md-1">
      <h2>Users</h2>

      <table class="table">
        <thead>
          <tr>
            <th>image</th>
            <th>name</th>
            <th colspan="3"></th>
          </tr>
        </thead>

        <tbody>
          <% @users.each do |user| %>
          <tr>
            <td><%= attachment_image_tag user, :profile_image, size: "40x40", fallback: "no_image.jpeg" %></td>
            <td><%= user.name %></td>
            <td><%= link_to "Show", user_path(user.id) %></td>
          </tr>
          <% end %>
        </tbody>
      </table>

    </div>
  </div>
</div>

app/views/users/show.html.erb
<div class="container px-5 px-sm-0">
  <div class="row">
    <div class="col-md-3">
      <%= render partial: "layouts/user_info", locals: {user: @user} %>
      <%= render partial: "layouts/new_book", locals: {book: @book} %>
    </div>

    <div class="col-md-8 offset-md-1">
      <h2>Books</h2>

      <table class="table">
        <thead>
          <tr>
            <th></th>
            <th>Title</th>
            <th>Opinion</th>
          </tr>
        </thead>

        <tbody>
          <% @books.each do |book| %>
          <tr>
            <td>
              <%= link_to user_path(book.user.id) do %>
                <%= attachment_image_tag @user, :profile_image, size: "40x40", fallback: "no_image.jpeg" %>
              <% end %>
            </td>
            <td><%= link_to book.title, book_path(book.id) %></td>
            <td><%= book.body %></td>
          </tr>
          <% end %>
        </tbody>
      </table>

    </div>
  </div>
</div>